// Reads lesson content and the router index off disk.
// The index is generated by scripts/build-index.ts; the .md files are
// produced by the transcriber project.

import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

export type LessonIndexEntry = {
  slug: string;
  title: string;
  week: string;
  video_url: string;
  duration_seconds: number | null;
  summary: string;
  md_path: string;
  video_id: string;
};

export type LoadedLesson = LessonIndexEntry & {
  md_content: string;
};

let indexCache: LessonIndexEntry[] | null = null;

function repoRoot(): string {
  // In dev + Node functions the CWD is the project root.
  return process.cwd();
}

export async function loadIndex(): Promise<LessonIndexEntry[]> {
  if (indexCache) return indexCache;
  const path = resolve(repoRoot(), 'data', 'index.json');
  const raw = await readFile(path, 'utf8');
  indexCache = JSON.parse(raw) as LessonIndexEntry[];
  return indexCache;
}

export async function loadLessons(slugs: string[]): Promise<LoadedLesson[]> {
  const index = await loadIndex();
  const bySlug = new Map(index.map((e) => [e.slug, e]));
  const out: LoadedLesson[] = [];
  for (const slug of slugs) {
    const entry = bySlug.get(slug);
    if (!entry) continue;
    const abs = resolve(repoRoot(), entry.md_path);
    try {
      const md_content = await readFile(abs, 'utf8');
      out.push({ ...entry, md_content });
    } catch {
      // Missing .md — the transcriber may not have produced one yet.
      out.push({ ...entry, md_content: `(no transcript available for ${entry.title})` });
    }
  }
  return out;
}
